[build]
base = ''
publish = 'dist'
command = 'STAGE=dev npm run build'

[context.production]
command = 'NODE_ENV=production npm run build:prod'

[context.deploy-preview]
command = 'STAGE=dev npm run build'

[context.branch-deploy]
command = 'STAGE=dev npm run build'

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
